name: DocC Archiving

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-visionos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
    
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
    
      - name: Resolve SwiftPM dependencies
        run: swift package resolve
    
      - name: Generate DocC Archive
        run: |
          xcodebuild docbuild \
            -scheme RoboKit \
            -derivedDataPath ${{ github.workspace }}/DerivedData \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=2.2' \
            -skipPackagePluginValidation \
            -skipMacroValidation
    
      - name: Process DocC Archive for Static Hosting
        run: |
          # locate the generated .doccarchive
          ARCHIVE_PATH=$(find "${{ github.workspace }}/DerivedData" -type d -name "*.doccarchive" | head -n 1)
          echo "Found DocC archive at: $ARCHIVE_PATH"
    
          OUTPUT_PATH="${{ github.workspace }}/docs"
          URL_BASE_PATH="NewTestDocc"
    
          xcrun docc process-archive transform-for-static-hosting \
            "$ARCHIVE_PATH" \
            --output-path "$OUTPUT_PATH" \
            --hosting-base-path "$URL_BASE_PATH" \
    
      - name: Commit and Push to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update DocC documentation for GitHub Pages"
          git push origin main
