name: RoboKit Unit Tests

on:
  push:        { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test-visionos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Resolve SwiftPM dependencies
        run: swift package resolve

      - name: Run tests on visionOS 2.2 Simulator
        run: |
          xcodebuild test \
            -scheme RoboKit \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=2.2' \
            -enableCodeCoverage YES
